/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advancedtopics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //
        //CompleteableFutureConcept singleFutures = new CompleteableFutureConcept();
        //singleFutures.handleSingleFuture();
        //futures.handleMutliplesFutures();
        //System.out.println(new App().getGreeting());

        //Player batsman = new Player()
    }
}
